INSERT INTO `Common` (`main`, `description`) VALUES
('Course Policies And Student Responsibilities', 'As a student of the course, you are required to abide by both the University Code of Conduct and the Student Code of Conduct. The Codes provide information on the responsibilities of all NTU students, as well as examples of midconduct and details about how student can report suspected misconduct. The university also has the Student Mental Health Policy. The policy sates the University\'s commitment to provideing a supportive envrionment for the holistic development of students, includeing the improvement of mental health and wellbeing. These policies and codes concering students can be found in the following link. <a href="http://www.ntu.edu.sg/SAO/Pages/Policies-concerning-students.aspx">http://www.ntu.edu.sg/SAO/Pages/Policies-concerning-students.aspx</a>'),
('Academic Integrity', 'Good academic work depends on honesty and ethical behavior. The quality of your work as a student relies on adhering to the principles of academic integrity and to the NTU Honor Code, a set of values shared by the whole university community. Truth, Trust and Justice are at the core of NTU\'s shared values.
As a student, it is important that you reconize your responsibilities in understanding and applying the principles of acadmeic integrity in all the work you do at NTU. Not knowing what is involved in maintaining academic integrity does not excuse academic dishonesty. You need to actively equip yourself with strategies to avoid all forms of academic dishonesty, including plagiarism, academic fraud, and collusion and cheating. If you are uncertain of the definitions of any of these terms, you should go to the academic integrity website for more information. Consult your instructor(s) if you need any clarificiation about the requirements of academic integrity in the course.')

INSERT INTO `graduateAttributes` (`ID`, `main`, `description`) VALUES
('a', 'Engineering Knowledge', 'Apply the knowledge of mathematics, natural science, engineering fundamentals, and an engineering specialisation to the solution of complex engineering problems.'),
('b', 'Problem Analysis', 'Identify, formulate, research literature, and analyse complex engineering problems reaching substantiated conclusion using first principles of mathematics, natural sciences, and egnineering sciences.'),
('c', 'Design/development of Solutions', 'Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for public health and safety, cultural, societal, and environmental considerations.'),
('d', 'Investigation', 'Conduct investigations of complex problems using research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of the information to provide valid conclusions.'),
('e', 'Modern Tool Usage', 'Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modelling to complex engineering activities with an understanding of the limitations.'),
('f', 'The engineer and Society', 'Apply reasoning informed by the contextual knowledge to assess societal, health, safety, legal, and cultural issues and the consequent responsibilities relevant to the professional engineering practice.'),
('g', 'Environment and Sustainability', 'Understand the impact of the professional engineering solutions in societal and environmental contexts, and demonstrate the knowledge of, and need for t h e sustainable development.'),
('h', 'Ethics', 'Apply ethical principles and commit to professional ethics and responsibilities and norms of the engineering practice.'),
('i', 'Individual and Team Work', 'Function effectively as an individual, and as a member or leader in diverse teams and in multidisciplinary settings.'),
('j', 'Communication', 'Communicate effectively on complex engineering activities with the engineering community and with society at large, such as, being able to comprehend and write effective reports and design documentation, make effective presentations, and give and receive clear instructions.'),
('k', 'Project Management and Finance', 'Demonstrate knowledge and understanding of t h e engineering and management principles and economic decision-making, and apply these to one’s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments.'),
('l', 'Life-long Learning', 'Recognise the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological change.')
