INSERT INTO `graduateAttributes` (`ID`, `main`, `description`) VALUES
('a', 'Engineering Knowledge', 'Apply the knowledge of mathematics, natural science, engineering fundamentals, and an engineering specialisation to the solution of complex engineering problems.'),
('b', 'Problem Analysis', 'Identify, formulate, research literature, and analyse complex engineering problems reaching substantiated conclusion using first principles of mathematics, natural sciences, and egnineering sciences.'),
('c', 'Design/development of Solutions', 'Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for public health and safety, cultural, societal, and environmental considerations.'),
('d', 'Investigation', 'Conduct investigations of complex problems using research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of the information to provide valid conclusions.'),
('e', 'Modern Tool Usage', 'Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modelling to complex engineering activities with an understanding of the limitations.'),
('f', 'The engineer and Society', 'Apply reasoning informed by the contextual knowledge to assess societal, health, safety, legal, and cultural issues and the consequent responsibilities relevant to the professional engineering practice.'),
('g', 'Environment and Sustainability', 'Understand the impact of the professional engineering solutions in societal and environmental contexts, and demonstrate the knowledge of, and need for t h e sustainable development.'),
('h', 'Ethics', 'Apply ethical principles and commit to professional ethics and responsibilities and norms of the engineering practice.'),
('i', 'Individual and Team Work', 'Function effectively as an individual, and as a member or leader in diverse teams and in multidisciplinary settings.'),
('j', 'Communication', 'Communicate effectively on complex engineering activities with the engineering community and with society at large, such as, being able to comprehend and write effective reports and design documentation, make effective presentations, and give and receive clear instructions.'),
('k', 'Project Management and Finance', 'Demonstrate knowledge and understanding of t h e engineering and management principles and economic decision-making, and apply these to one’s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments.'),
('l', 'Life-long Learning', 'Recognise the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological change.')
